FlujoPoligonos: FlujoPoligonos.o FlujoPoligonosTest.o
	g++ FlujoPoligonos.o FlujoPoligonosTest.o -o FlujoPoligonos 

FlujoPoligonos.o: FlujoPoligonos.cpp
	g++ -c FlujoPoligonos.cpp

FlujoPoligonosTest.o: FlujoPoligonosTest.cpp
	g++ -c FlujoPoligonosTest.cpp